### ISSUE TITLE
Something better than Creditor/Debtor

### ISSUE THREAD

**Issue by markabird** [w3c/market-data-odrl-profile#17]
So far, we've used the terms "Debtor" and "Creditor" when discussing Duties. The Debtor is the party that has the responsibility to fulfill the Duty for the benefit (or at the insistence) of the Creditor. This makes logical sense because the Debtor "owes" some action to the Creditor.

However, these terms can be confusing because we're used to thinking about creditors and debtors in a monetary sense, where the debtor has an obligation to pay to the creditor. But in our parlance, the Debtor can be the party that "owes" the creation of an invoice to the Creditor. In this case, before the invoice is created, the Debtor is the party that has to make the invoice in order to get paid!

Let's use this thread to suggest other term pairs that can be used when describing Duties. What two terms most clearly define the party that requires a Duty, and the party to whom falls the responsibility of fulfilling the Duty?

Please submit suggestions below, and then we'll agree on a favorite on Wednesday's call.

**Comment by jo-rabin-db** [comment]
Some thing like:
actor -> target
giver -> receiver
subject -> object

**Comment by benedictws** [comment]
Obligatee -> Obligator - ugly words, but the meaning fits perfectly

**Comment by jo-rabin-db** [comment]
Does obligator actually mean what we need it to mean?

obligatee (plural obligatees). A person who is obligated by law to do something

that's is OK for the party on whom there is a duty

obligator (plural obligators) (law) One who establishes an obligation under law

that reads like it's the person setting the obligation rather than the target of the action carried out as part of the obligation

**Comment by epritce** [comment]
Licensor-> Licensee

**Comment by markabird** [comment]
It's clumsy but how about:

Requiring Party -> Responsible Party

**Comment by benedictws** [comment]
Three worked examples:

**Actor/Receiver**
_Usage notification example_
1. The `actor` must notify the `receiver` when they first use the data

_Audit example (roles swap between steps)_
1. The `actor` must notify the `receiver` of their desire to audit data usage.

2. The `actor` must consent to the `receiver`'s  audit of their data usage within 30 days.
<br>

**Subject/Object**
_Usage notification example_
1. The `subject` of the duty must notify the `object` of the duty when they first use the data

_Audit example (roles swap between steps)_
1. The `subject` of the duty must notify the `object` of the duty of their desire to audit data usage.

2. The `subject` of the duty must consent to the `object` of the duty's  audit of their data usage within 30 days.
<br>

**Promisor/Promisee**
_Usage notification example_
1. The `promisor` must notify the `promisee` when they first use the data

_Audit example (roles swap between steps)_
1. The `promisor` must notify the `promisee` of their desire to audit data usage.

2. The `promisor` must consent to the `promisee`'s  audit of their data usage within 30 days.
