### ISSUE TITLE
Roles in the Data Supply Chain

### ISSUE THREAD

**Issue by benedictws** [w3c/market-data-odrl-profile#4]
We tend to think of organisations like Refinitiv and Bloomberg as vendors of data. Sometimes we call them carriers.

We describe the Australian Securities Exchange as a supplier or originator of data.

Then banks like HSBC are consumers of the data.

But in reality, these companies play all of these roles. HSBC is likely a consumer, vendor, and originator of data, as are the other companies listed above.

In the supply chain, we all play different roles at different times. It's a complex supply chain!

But what are the minimum number of roles that we need to model in order to describe it?

I'd like to suggest four: 

>Originator: A party that generates/owns a resource 
>Provider: A party that distributes a resource to a consumer
>Consumer: A party that uses a resource
>Service Provider: External organisation contracted by a party (or its affiliated companies) to assist in the delivery of data services.

What - no **Vendor**? Seems to me that's covered by the term Provider.

No **Carrier**? No, again, I think that's covered by the term Provider.

Do we need to distinguish between the originator of the data and its **owner**? Maybe. But when the Deutsche Boerse provides data from the Bombay Stock Exchange, it's acting as a Provider. The Bombay Stock Exchange remains the Originator. We don't need to split out the owner. But are there use cases where we must?

No **Sub-Contractors**? Seems to me that's covered by the term Service Provider.

No **Sub-Vendors**? Here I think we have the pattern Provider -> Provider -> Consumer, with the sub-vendor acting in the middle. Beyond acting as a Provider in a particular sequence, is there anything special about this role such that it deserves a new term? I don't think so.

What are we missing?

**Comment by islavin** [comment]
In my view, the difference between a **Provider** and a **Service Provider** in the above model is presence of enrichments or intellectual property "overrides" that a Service Provider may add to data that transits their network on its way to the Consumer.  However, market data organizations in all manner of firms are Service Providers to their own companies, often attaching internal rules, enrichments and processes to data on its way to the ultimate Consumers inside their firms.  Similarly, such organizations can transform and enrich content generated by internal data sources (Originators) before it is sent to other Providers for ultimate distribution to Customers outside their firewalls.
I would, therefore, suggest simplifying the model by merging **Service Provider** and **Provider** roles.

**Comment by primell** [comment]
I feel there are two separate areas that need to be accommodated here

1.	Rights and obligations related to market data as a resource and that are passed down the market data supply chain from party to party.

2.	Services that support the activities of parties in the supply chain but that may be constrained by the above rights and obligations. Parties that provide such services are not a material part of the chain (they are not given rights over the resource)

So I’d prefer to see a distinction between the (Resource) **Provider** in the supply chain and such “service providers” to accommodate the above. There may be a better term for them, perhaps “**Service Facilitator**”?

Re no “**Vendor**”? I can live with that. My assumption is that each party in a chain of **Providers** could each add value to the **Resource** , provided compliance is maintained with the agreement with their supplier of the **Resource** – the previous **Provider** in the supply chain.

Re no “sub-contractors”. I think this comes under the **Service Facilitator** role. Any party in the supply chain can (subject to the agreement with their supplier as above) sub-contract with a **Service Facilitator**.

Re no “sub-vendor”. I agree not required.

Lastly each party-to-party agreement in the supply chain is generically I think a supplier-to-customer relationship. Each party may internally view each customer as a **Consumer** or onwards **Provider** of the **Resource**. But they may also have special terms for their own role as **Provider** (e.g. “Vendor”) or for their own customer’s role (e.g. “Sub-vendor”, “Redistributor” etc) from the perspective of their own business.

Hope that helps!

**Comment by benedictws** [comment]
I'm sold on the term **Service Facilitator**. It's a significant improvement on **Service Provider**.

I'm also sold on the distinction between roles that play a part in the transfer of rights and obligations and those that don't.

As you say @primell, the difference between a **Provider** and a **Service Facilitator** is that the former does transfer rights and the latter does not.

So @islavin, you act primarily as a **Provider** to your internal Consumers as you decide what rights and obligations are passed through to them. Does this feel right?

The reason I'm keen to make this distinction is because some licenses do.  The DBAG non-display license puts a **Duty** on the assignee to notify DBAG of the use of service facilitators:
>```
>:D3     a                      odrl:Duty ;
>         nl:creditor            <https://permid.org/1-4298007872> ; # DBAG
>         odrl:action            [   a                 md:Notify ;
>                                    md:actionScope    md:ServiceFacilitator ;
>                                    odrl:count        "1"^^xsd:int
>                                ] ;
>         md:otherParties        md:ServiceFacilitator .
>```

This effectively says that if other parties have access to the data, and if these other parties are **Service Facilitators**, then the assignee must notify DBAG of their use of service facilitators.

Are there any other roles that licenses are sensitive to?

**Comment by benedictws** [comment]
Updating the definition of the roles to take account of the discussion:

> **Originator**: A party that generates/owns a resource and acts as an assigner of the rights and obligations controlling the use of that resource by third-parties
> **Provider**: A party that distributes a resource to a consumer and acts as an assigner of the rights and obligations controlling the use of that resource by third-parties
> **Consumer**: A party that receives a resource and acts as an assignee of the rights and obligations controlling the use of that resource
> **Service Facilitator**: An external organisation contracted by a Party (or its affiliated companies) to assist in the delivery of data services.

In this picture, the roles in play when an exchange delivers data to a vendor for onward distribution to a bank would look as follows:

(**Orignator**): the exchange -> (**Consumer** -> **Provider**): the vendor -> (**Consumer** -> **Provider**): the market data function in the bank -> (**Consumer**): the end user in the bank

Maybe I have tightened the definitions too far?

**Comment by benedictws** [comment]
Pulling in relevant comments from another thread: 

https://github.com/w3c/market-data-odrl-profile/issues/3#issuecomment-642028964

https://github.com/w3c/market-data-odrl-profile/issues/3#issuecomment-647446593

**Comment by markabird** [comment]
It might be useful to distinguish between the Originator of the data and the Administrator of the data. In many instances a Provider or Consumer will license with a party that is not technically the creator or owner of the data product, but has been assigned administration rights for the product.

**Comment by benedictws** [comment]
Does this mean @markabird that the Administrator is the legal entity that makes the rights assignment (aka the Assigner)?

If not, would you be happy for the Administrator to be described as a Service Facilitator (facilitating administrative and licensing workflows)?

**Comment by markabird** [comment]
That's correct, somewhat counter-intuitively it's the Administrator that makes the rights assignment. The actual creator of the data product is largely irrelevant to the data rights supply chain, it's just interesting that what we're calling the Originator is often not themselves the actual originator of the data product.

I guess my suggestion is not that we change or add any terms, but that we be aware that the Originator in terms of this thread may be a different party than the actual creator of the data product.

**Comment by benedictws** [comment]
Hmm, I think this requires a new term. Both Originators and Providers are involved in the actual, physical distribution of the data. By the sounds of it, an Administrator is not.

**Comment by LBPerdue** [comment]
I wonder what KOSCOM would be classified as?

**Comment by benedictws** [comment]
Hmm, based on a quick internet search, I'd say they play the role of a Provider rather than that of an Administrator. From Wikipedia: "Major Korean financial firms have subscription to the Koscom's online trading services including market news, price quotes and financial market data."

I don't think play the role of an Originator - that's left to their majority shareholder, the Korea Exchange.

Does this fit with your sense of them @LBPerdue?

**Comment by benedictws** [comment]
Now reflected in the profile: https://w3c.github.io/market-data-odrl-profile/md-odrl-profile.html#Party%20Roles
